info.application.name=HelloWorld
business.application.name=A Demo for Spring Boot hello World!
info.application.author.name=Homer Simpson
info.application.author.bio=Nuclear Safety Inspector, Former Technical Supervisor
business.service.electrical.elements=CiccioPaciccio
business.service.element=Alan Ford
spring.application.name=Bootstrap Spring Boot %1
server.port=9092

# Logging
logging.level.root=INFO
logging.level.com.example.springdemo=DEBUG

# Cartella log
app.log.path=logs

# --- H2 Database ---
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Crea automaticamente le tabelle dalle entity
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL in console
spring.jpa.show-sql=true

# Dialetto Hibernate per H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

🔍
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#export DB_URL=jdbc:mysql://localhost:3306/miodb
#export DB_USER=marco
#export DB_PASS=supersegreta
